# Generated by Django 3.1.4 on 2021-01-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('primary_contact', models.CharField(max_length=50)),
                ('primary_phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField()),
                ('job_start_date', models.DateField(auto_now_add=True)),
                ('job_end_date', models.DateField()),
                ('last_updated_date', models.DateField(auto_now=True)),
                ('number_of_lights', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_style', models.CharField(max_length=50)),
                ('number_of_leds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('alternate_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LightCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lights', models.PositiveIntegerField()),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('light', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.light')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='light',
            field=models.ManyToManyField(related_name='lights', through='jobs.LightCount', to='jobs.Light'),
        ),
        migrations.AddField(
            model_name='job',
            name='ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.ride'),
        ),
    ]
