# Generated by Django 3.1.5 on 2021-01-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='jobs.customer'),
        ),
    ]
