# Generated by Django 3.1.5 on 2021-01-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_ride_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='customer',
        ),
        migrations.AddField(
            model_name='ride',
            name='customers',
            field=models.ManyToManyField(related_name='rides', to='jobs.Customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='light',
            field=models.ManyToManyField(related_name='jobs', through='jobs.LightCount', to='jobs.Light'),
        ),
    ]
