# Generated by Django 3.1.5 on 2021-01-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210106_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.customer'),
        ),
    ]
