# Generated by Django 3.1.6 on 2021-03-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='number_of_leds',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='rides', to='jobs.Customer'),
        ),
    ]
